Repository ita-social-projects/dokazovi-be, pull requests merged in 2021-07, with the labels that each got.

#370 Issue 364 implement api enpoint for information page
  src/main/java/com/softserveinc/dokazovi/config/WebSecurityConfig.java
  src/main/java/com/softserveinc/dokazovi/controller/EndPoints.java
  src/main/java/com/softserveinc/dokazovi/controller/PlatformInformationController.java
  src/main/java/com/softserveinc/dokazovi/dto/info/PlatformInformationDTO.java
  src/main/java/com/softserveinc/dokazovi/entity/PlatformInformationEntity.java
  src/main/java/com/softserveinc/dokazovi/entity/enumerations/RolePermission.java
  src/main/java/com/softserveinc/dokazovi/mapper/PlatformInformationMapper.java
  src/main/java/com/softserveinc/dokazovi/repositories/PlatformInformationRepository.java
  src/main/java/com/softserveinc/dokazovi/service/PlatformInformationService.java
  src/main/java/com/softserveinc/dokazovi/service/impl/PlatformInformationServiceImpl.java
  src/main/resources/db/migration/V11__add_platform_information_table.sql
  src/main/resources/db/testdata/V11.1__add_platform_information_demo_data.sql
  src/main/resources/db/testdata/V11.2__add_role_permissions.sql
  src/test/java/com/softserveinc/dokazovi/controller/PlatformInformationControllerTest.java
  src/test/java/com/softserveinc/dokazovi/mapper/PlatformInformationMapperTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/PlatformInformationServiceImplTest.java
Labels: backend

#365 Feature /add post migration data
  src/main/resources/db/testdata/V11.3__add_posts_demo_data.sql
Labels: backend

#383 The functionality PUT endpoint of the PlatformInformationController was modified
  src/main/java/com/softserveinc/dokazovi/mapper/PlatformInformationMapper.java
  src/main/resources/db/testdata/V11.4__add_updated_platform_information_demo_data.sql
Labels: backend

#384 Issue 377 add field to postentity
  src/main/java/com/softserveinc/dokazovi/controller/EndPoints.java
  src/main/java/com/softserveinc/dokazovi/controller/PostController.java
  src/main/java/com/softserveinc/dokazovi/dto/post/PostDTO.java
  src/main/java/com/softserveinc/dokazovi/dto/post/PostSaveFromUserDTO.java
  src/main/java/com/softserveinc/dokazovi/entity/PostEntity.java
  src/main/java/com/softserveinc/dokazovi/repositories/PostRepository.java
  src/main/java/com/softserveinc/dokazovi/service/PostService.java
  src/main/java/com/softserveinc/dokazovi/service/impl/PostServiceImpl.java
  src/main/resources/db/migration/V12__add_importantImageUrl_to_posts_table.sql
  src/test/java/com/softserveinc/dokazovi/controller/PostControllerTest.java
Labels: backend

#379 Establish linkage between frontend and backend releases
  src/main/resources/application.properties
Labels: backend

#385 Merge from develop to release
  src/main/java/com/softserveinc/dokazovi/config/WebSecurityConfig.java
  src/main/java/com/softserveinc/dokazovi/controller/EndPoints.java
  src/main/java/com/softserveinc/dokazovi/controller/PlatformInformationController.java
  src/main/java/com/softserveinc/dokazovi/controller/PostController.java
  src/main/java/com/softserveinc/dokazovi/dto/info/PlatformInformationDTO.java
  src/main/java/com/softserveinc/dokazovi/dto/post/PostDTO.java
  src/main/java/com/softserveinc/dokazovi/dto/post/PostSaveFromUserDTO.java
  src/main/java/com/softserveinc/dokazovi/entity/PlatformInformationEntity.java
  src/main/java/com/softserveinc/dokazovi/entity/PostEntity.java
  src/main/java/com/softserveinc/dokazovi/entity/enumerations/RolePermission.java
  src/main/java/com/softserveinc/dokazovi/mapper/PlatformInformationMapper.java
  src/main/java/com/softserveinc/dokazovi/repositories/PlatformInformationRepository.java
  src/main/java/com/softserveinc/dokazovi/repositories/PostRepository.java
  src/main/java/com/softserveinc/dokazovi/service/PlatformInformationService.java
  src/main/java/com/softserveinc/dokazovi/service/PostService.java
  src/main/java/com/softserveinc/dokazovi/service/impl/PlatformInformationServiceImpl.java
  src/main/java/com/softserveinc/dokazovi/service/impl/PostServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V11__add_platform_information_table.sql
  src/main/resources/db/migration/V12__add_importantImageUrl_to_posts_table.sql
  src/main/resources/db/testdata/V11.1__add_platform_information_demo_data.sql
  src/main/resources/db/testdata/V11.2__add_role_permissions.sql
  src/main/resources/db/testdata/V11.3__add_posts_demo_data.sql
  src/main/resources/db/testdata/V11.4__add_updated_platform_information_demo_data.sql
  src/test/java/com/softserveinc/dokazovi/controller/PlatformInformationControllerTest.java
  src/test/java/com/softserveinc/dokazovi/controller/PostControllerTest.java
  src/test/java/com/softserveinc/dokazovi/mapper/PlatformInformationMapperTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/PlatformInformationServiceImplTest.java
Labels: backend

#388 Fix: Post migration data
  src/main/resources/db/testdata/V11.5__fix_add_posts_demo_data.sql
Labels: backend, bug

#390 The bug regarding saving a post (article) was fixed.
  src/main/java/com/softserveinc/dokazovi/service/impl/PostServiceImpl.java
  src/test/java/com/softserveinc/dokazovi/service/impl/PostServiceImplTest.java
Labels: backend, bug

#391 Merge develop into release
  src/main/java/com/softserveinc/dokazovi/service/impl/PostServiceImpl.java
  src/main/resources/db/testdata/V11.5__fix_add_posts_demo_data.sql
  src/test/java/com/softserveinc/dokazovi/service/impl/PostServiceImplTest.java
Labels: backend, bug

#393 Fix: SQL query bug
  src/main/java/com/softserveinc/dokazovi/repositories/PostRepository.java
Labels: backend, bug

#394 Merge develop into release
  src/main/java/com/softserveinc/dokazovi/repositories/PostRepository.java
Labels: SQL, backend, bug

#398 Merge release to master
  src/main/java/com/softserveinc/dokazovi/config/WebSecurityConfig.java
  src/main/java/com/softserveinc/dokazovi/controller/EndPoints.java
  src/main/java/com/softserveinc/dokazovi/controller/PlatformInformationController.java
  src/main/java/com/softserveinc/dokazovi/controller/PostController.java
  src/main/java/com/softserveinc/dokazovi/dto/info/PlatformInformationDTO.java
  src/main/java/com/softserveinc/dokazovi/dto/post/PostDTO.java
  src/main/java/com/softserveinc/dokazovi/dto/post/PostSaveFromUserDTO.java
  src/main/java/com/softserveinc/dokazovi/entity/PlatformInformationEntity.java
  src/main/java/com/softserveinc/dokazovi/entity/PostEntity.java
  src/main/java/com/softserveinc/dokazovi/entity/enumerations/RolePermission.java
  src/main/java/com/softserveinc/dokazovi/mapper/PlatformInformationMapper.java
  src/main/java/com/softserveinc/dokazovi/repositories/PlatformInformationRepository.java
  src/main/java/com/softserveinc/dokazovi/repositories/PostRepository.java
  src/main/java/com/softserveinc/dokazovi/service/PlatformInformationService.java
  src/main/java/com/softserveinc/dokazovi/service/PostService.java
  src/main/java/com/softserveinc/dokazovi/service/impl/PlatformInformationServiceImpl.java
  src/main/java/com/softserveinc/dokazovi/service/impl/PostServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V11__add_platform_information_table.sql
  src/main/resources/db/migration/V12__add_importantImageUrl_to_posts_table.sql
  src/main/resources/db/testdata/V11.1__add_platform_information_demo_data.sql
  src/main/resources/db/testdata/V11.2__add_role_permissions.sql
  src/main/resources/db/testdata/V11.3__add_posts_demo_data.sql
  src/main/resources/db/testdata/V11.4__add_updated_platform_information_demo_data.sql
  src/main/resources/db/testdata/V11.5__fix_add_posts_demo_data.sql
  src/test/java/com/softserveinc/dokazovi/controller/PlatformInformationControllerTest.java
  src/test/java/com/softserveinc/dokazovi/controller/PostControllerTest.java
  src/test/java/com/softserveinc/dokazovi/mapper/PlatformInformationMapperTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/PlatformInformationServiceImplTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/PostServiceImplTest.java
Labels: backend

#400 Change password verification by email
  build.gradle
  src/main/java/com/softserveinc/dokazovi/annotations/PasswordMatches.java
  src/main/java/com/softserveinc/dokazovi/controller/AuthController.java
  src/main/java/com/softserveinc/dokazovi/controller/EndPoints.java
  src/main/java/com/softserveinc/dokazovi/controller/UserController.java
  src/main/java/com/softserveinc/dokazovi/dto/user/UserEmailDTO.java
  src/main/java/com/softserveinc/dokazovi/dto/user/UserEmailPasswordDTO.java
  src/main/java/com/softserveinc/dokazovi/dto/user/UserPasswordDTO.java
  src/main/java/com/softserveinc/dokazovi/entity/PasswordResetTokenEntity.java
  src/main/java/com/softserveinc/dokazovi/repositories/PasswordResetTokenRepository.java
  src/main/java/com/softserveinc/dokazovi/repositories/PostRepository.java
  src/main/java/com/softserveinc/dokazovi/repositories/UserRepository.java
  src/main/java/com/softserveinc/dokazovi/service/MailSenderService.java
  src/main/java/com/softserveinc/dokazovi/service/PasswordResetTokenService.java
  src/main/java/com/softserveinc/dokazovi/service/UserService.java
  src/main/java/com/softserveinc/dokazovi/service/impl/MailSenderServiceImpl.java
  src/main/java/com/softserveinc/dokazovi/service/impl/PasswordResetTokenServiceImpl.java
  src/main/java/com/softserveinc/dokazovi/service/impl/UserServiceImpl.java
  src/main/java/com/softserveinc/dokazovi/util/MailSenderUtil.java
  src/main/java/com/softserveinc/dokazovi/validator/PasswordMatchesValidator.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V13__add_password_reset_tokens_table.sql
  src/main/resources/db/testdata/V1.6__add_user_for_reset_password.sql
  src/test/java/com/softserveinc/dokazovi/controller/AuthControllerTest.java
  src/test/java/com/softserveinc/dokazovi/controller/UserControllerTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/PasswordResetTokenServiceImplTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/UserServiceImplTest.java
  src/test/java/com/softserveinc/dokazovi/util/MailSenderServiceImplTest.java
  src/test/java/com/softserveinc/dokazovi/validator/PasswordMatchesValidatorTest.java
Labels: backend

#402 rename testdata sql script to correct version
  src/main/resources/db/testdata/V13.1__add_user_for_reset_password.sql
Labels: backend, bug

#401 add endpoint for Expert's Posts by status
  src/main/java/com/softserveinc/dokazovi/controller/EndPoints.java
  src/main/java/com/softserveinc/dokazovi/controller/PostController.java
  src/main/java/com/softserveinc/dokazovi/service/PostService.java
  src/main/java/com/softserveinc/dokazovi/service/impl/PostServiceImpl.java
  src/test/java/com/softserveinc/dokazovi/controller/PostControllerTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/PostServiceImplTest.java
Labels: backend

#403 Merge develop to release
  build.gradle
  src/main/java/com/softserveinc/dokazovi/annotations/PasswordMatches.java
  src/main/java/com/softserveinc/dokazovi/controller/AuthController.java
  src/main/java/com/softserveinc/dokazovi/controller/EndPoints.java
  src/main/java/com/softserveinc/dokazovi/controller/PostController.java
  src/main/java/com/softserveinc/dokazovi/controller/UserController.java
  src/main/java/com/softserveinc/dokazovi/dto/user/UserEmailDTO.java
  src/main/java/com/softserveinc/dokazovi/dto/user/UserEmailPasswordDTO.java
  src/main/java/com/softserveinc/dokazovi/dto/user/UserPasswordDTO.java
  src/main/java/com/softserveinc/dokazovi/entity/PasswordResetTokenEntity.java
  src/main/java/com/softserveinc/dokazovi/repositories/PasswordResetTokenRepository.java
  src/main/java/com/softserveinc/dokazovi/repositories/PostRepository.java
  src/main/java/com/softserveinc/dokazovi/repositories/UserRepository.java
  src/main/java/com/softserveinc/dokazovi/service/MailSenderService.java
  src/main/java/com/softserveinc/dokazovi/service/PasswordResetTokenService.java
  src/main/java/com/softserveinc/dokazovi/service/PostService.java
  src/main/java/com/softserveinc/dokazovi/service/UserService.java
  src/main/java/com/softserveinc/dokazovi/service/impl/MailSenderServiceImpl.java
  src/main/java/com/softserveinc/dokazovi/service/impl/PasswordResetTokenServiceImpl.java
  src/main/java/com/softserveinc/dokazovi/service/impl/PostServiceImpl.java
  src/main/java/com/softserveinc/dokazovi/service/impl/UserServiceImpl.java
  src/main/java/com/softserveinc/dokazovi/util/MailSenderUtil.java
  src/main/java/com/softserveinc/dokazovi/validator/PasswordMatchesValidator.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V13__add_password_reset_tokens_table.sql
  src/main/resources/db/testdata/V13.1__add_user_for_reset_password.sql
  src/test/java/com/softserveinc/dokazovi/controller/AuthControllerTest.java
  src/test/java/com/softserveinc/dokazovi/controller/PostControllerTest.java
  src/test/java/com/softserveinc/dokazovi/controller/UserControllerTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/PasswordResetTokenServiceImplTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/PostServiceImplTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/UserServiceImplTest.java
  src/test/java/com/softserveinc/dokazovi/util/MailSenderServiceImplTest.java
  src/test/java/com/softserveinc/dokazovi/validator/PasswordMatchesValidatorTest.java
Labels: backend

#409 get back previous variant of query findAllByImportantImageUrlDesc
  src/main/java/com/softserveinc/dokazovi/repositories/PostRepository.java
Labels: backend, bug

#410 Deploy develop to release
  src/main/java/com/softserveinc/dokazovi/repositories/PostRepository.java
Labels: backend, bug

#411 Update endpoints for expert posts and post types by status
  src/main/java/com/softserveinc/dokazovi/controller/PostController.java
  src/main/java/com/softserveinc/dokazovi/controller/PostTypesController.java
  src/main/java/com/softserveinc/dokazovi/repositories/PostTypeRepository.java
  src/main/java/com/softserveinc/dokazovi/service/PostTypeService.java
  src/main/java/com/softserveinc/dokazovi/service/impl/PostTypeServiceImpl.java
  src/test/java/com/softserveinc/dokazovi/controller/PostControllerTest.java
  src/test/java/com/softserveinc/dokazovi/controller/PostTypesControllerTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/PostTypeServiceImplTest.java
Labels: backend

#412 The DB was populated with new users (1 admin & 18 authors)
  src/main/resources/db/testdata/V13.2__add_new_users.sql
Labels: SQL, backend

#415 Bugfix remove limit of pictures in corousel
  src/main/java/com/softserveinc/dokazovi/controller/PostController.java
  src/main/java/com/softserveinc/dokazovi/repositories/PostRepository.java
  src/main/java/com/softserveinc/dokazovi/service/impl/PostServiceImpl.java
  src/test/java/com/softserveinc/dokazovi/controller/PostControllerTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/PostServiceImplTest.java
Labels: backend, bug

#416 Merge develop to release
  src/main/java/com/softserveinc/dokazovi/controller/PostController.java
  src/main/java/com/softserveinc/dokazovi/repositories/PostRepository.java
  src/main/java/com/softserveinc/dokazovi/service/impl/PostServiceImpl.java
  src/test/java/com/softserveinc/dokazovi/controller/PostControllerTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/PostServiceImplTest.java
Labels: backend, bug

#417 Merge release to master
  src/main/java/com/softserveinc/dokazovi/controller/PostController.java
  src/main/java/com/softserveinc/dokazovi/repositories/PostRepository.java
  src/main/java/com/softserveinc/dokazovi/service/impl/PostServiceImpl.java
  src/test/java/com/softserveinc/dokazovi/controller/PostControllerTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/PostServiceImplTest.java
Labels: backend, bug

#418 Issue add testdata reset password
  src/main/resources/db/testdata/V13.3__add_user_for_reset_password_demo.sql
Labels: backend, bug

#419 Merge develop to release
  src/main/resources/db/testdata/V13.3__add_user_for_reset_password_demo.sql
Labels: SQL, backend

#420 Merge release to master
  src/main/resources/db/testdata/V13.3__add_user_for_reset_password_demo.sql
Labels: backend

#423 An institution and two users were added
  src/main/resources/db/testdata/V13.4__add_new_users.sql
Labels: SQL, backend

#425 Merge release into master
  src/main/resources/db/testdata/V13.4__add_new_users.sql
Labels: SQL, backend
