Repository ita-social-projects/dokazovi-be, pull requests merged in 2021-01, with the labels that each got.

#148 Docs/readme
  README.md
Labels: backend, documentation

#149 Validation of DTO
  src/main/java/com/softserveinc/dokazovi/dto/direction/DirectionDTO.java
  src/main/java/com/softserveinc/dokazovi/dto/post/PostSaveFromUserDTO.java
  src/main/java/com/softserveinc/dokazovi/dto/post/PostTypeDTO.java
  src/main/java/com/softserveinc/dokazovi/dto/source/SourceDTO.java
  src/main/java/com/softserveinc/dokazovi/dto/tag/TagDTO.java
  src/main/java/com/softserveinc/dokazovi/dto/tag/TagSaveDTO.java
Labels: backend

#150 Endpoint "Get Post By Id"
  src/main/java/com/softserveinc/dokazovi/controller/EndPoints.java
  src/main/java/com/softserveinc/dokazovi/controller/PostController.java
  src/main/java/com/softserveinc/dokazovi/controller/UserController.java
  src/main/java/com/softserveinc/dokazovi/service/PostService.java
  src/main/java/com/softserveinc/dokazovi/service/impl/PostServiceImpl.java
  src/test/java/com/softserveinc/dokazovi/controller/PostControllerTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/PostServiceImplTest.java
Labels: Note Page, Post Page, Video Page, backend

#154 Feature/users refactoring
  gradle.properties
  src/main/java/com/softserveinc/dokazovi/entity/CharityEntity.java
  src/main/java/com/softserveinc/dokazovi/entity/DirectionEntity.java
  src/main/java/com/softserveinc/dokazovi/entity/DoctorEntity.java
  src/main/java/com/softserveinc/dokazovi/entity/InstitutionEntity.java
  src/main/java/com/softserveinc/dokazovi/entity/PostEntity.java
  src/main/java/com/softserveinc/dokazovi/entity/UserEntity.java
  src/main/java/com/softserveinc/dokazovi/mapper/PostMapper.java
  src/main/java/com/softserveinc/dokazovi/mapper/UserMapper.java
  src/main/java/com/softserveinc/dokazovi/repositories/DoctorRepository.java
  src/main/java/com/softserveinc/dokazovi/repositories/PostRepository.java
  src/main/java/com/softserveinc/dokazovi/repositories/UserRepository.java
  src/main/java/com/softserveinc/dokazovi/service/UserService.java
  src/main/java/com/softserveinc/dokazovi/service/impl/UserServiceImpl.java
  src/main/resources/application-dev.properties
  src/main/resources/db/migration/V20__separate_user_and_doctor_entities.sql
  src/main/resources/db/migration/V21__add_published_posts_rating_columns_doctors.sql
  src/main/resources/db/migration/V22__add_demo_data_for_doctor_table_separation.sql
  src/main/resources/db/migration/V23__fill_color_column_for_directions.sql
  src/main/resources/db/testdata/afterMigrate.sql
  src/test/java/com/softserveinc/dokazovi/mapper/PostMapperTest.java
  src/test/java/com/softserveinc/dokazovi/mapper/UserMapperTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/PostServiceImplTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/UserServiceImplTest.java
Labels: backend

#153 feature: new role implementation
  src/main/java/com/softserveinc/dokazovi/controller/AuthController.java
  src/main/java/com/softserveinc/dokazovi/controller/DirectionController.java
  src/main/java/com/softserveinc/dokazovi/controller/PostController.java
  src/main/java/com/softserveinc/dokazovi/controller/RegionController.java
  src/main/java/com/softserveinc/dokazovi/controller/TagController.java
  src/main/java/com/softserveinc/dokazovi/controller/UserController.java
  src/main/java/com/softserveinc/dokazovi/controller/VersionController.java
  src/main/java/com/softserveinc/dokazovi/entity/RoleEntity.java
  src/main/java/com/softserveinc/dokazovi/entity/UserEntity.java
  src/main/java/com/softserveinc/dokazovi/entity/enumerations/RolePermission.java
  src/main/java/com/softserveinc/dokazovi/security/TokenAuthenticationFilter.java
  src/main/java/com/softserveinc/dokazovi/security/UserPrincipal.java
  src/main/java/com/softserveinc/dokazovi/security/oauth2/CustomOAuth2UserService.java
  src/main/resources/db/migration/V24__New_roles_implementation.sql
  src/test/java/com/softserveinc/dokazovi/security/CustomUserDetailsServiceTest.java
  src/test/java/com/softserveinc/dokazovi/security/TokenProviderTest.java
  src/test/java/com/softserveinc/dokazovi/service/impl/ProviderServiceImplTest.java
Labels: backend

#156 BE - Delete nested validation
  src/main/java/com/softserveinc/dokazovi/dto/post/PostSaveFromUserDTO.java
Labels: Article Page, Note Page, Video Page, backend

#164 BE - Add more Demo posts for QC
  src/main/resources/db/migration/V26__add_demo_data_for_qc.sql
Labels: backend
